Repository JuliaFEM/Materials.jl, pull requests merged in 2018-09, with the labels that each got.

#18 Changes to abstract material
  REQUIRE
  src/Materials.jl
  test/REQUIRE
Labels: fix

#15 Ideal plastic material
  docs/src/figs/one_element_ideal_plastic.png
  docs/src/figs/plastic_joing.png
  examples/one_element_ideal_plastic.jl
  src/Materials.jl
  src/idealplastic.jl
  test/runtests.jl
  test/test_idealplastic.jl
Labels: new feature

#23 Simulator now uses material postprocess
  src/simulator.jl
Labels: enhancement

#10 Implementation of Chaboche material model
  REQUIRE
  examples/continuum.jl
  examples/one_elem_disp_chaboche.jl
  examples/one_elem_disp_chaboche/comparison_with_commercial.png
  examples/one_elem_disp_chaboche/unitelement_results.rpt
  examples/one_elem_disp_chaboche_refactored.jl
  src/Materials.jl
  src/chaboche.jl
  test/test_chaboche.jl
  test/test_chaboche/unitelement_results.rpt
Labels: new feature

#24 Add viscoplastic material with Norton rule
  src/Materials.jl
  src/viscoplastic.jl
  test/runtests.jl
  test/test_viscoplastic.jl
  test/test_viscoplastic/plot_material.jl
Labels: new feature

#29 Implement solver for mechanical material
  .travis.yml
  examples/one_element_ideal_plastic.jl
  examples/one_element_ideal_plastic/uniaxial_strain.svg
  src/Materials.jl
  src/chaboche.jl
  src/idealplastic.jl
  src/mecamatso.jl
  src/simulator.jl
  src/viscoplastic.jl
  test/runtests.jl
  test/test_idealplastic.jl
  test/test_mecamatso.jl
  test/test_viscoplastic.jl
Labels: new feature

#28 Improvements to chaboche.jl [WIP]
  examples/one_elem_disp_chaboche.jl
  examples/one_elem_disp_chaboche_refactored.jl
  src/Materials.jl
  src/chaboche.jl
  src/viscoplastic.jl
  test/test_chaboche.jl
Labels: enhancement

#35 Modifications to mecamatso
  src/Materials.jl
  src/mecamatso.jl
  test/runtests.jl
  test/test_idealplastic_shear.jl
  test/test_mecamatso.jl
Labels: enhancement

#39 Moved FEMBase dependencies to FEMMaterials
  Project_.toml
  REQUIRE
  src/Materials.jl
  src/chaboche.jl
  src/idealplastic.jl
  src/mecamatso.jl
  src/simulator.jl
  src/uniaxial_increment.jl
  src/viscoplastic.jl
  test/REQUIRE
  test/runtests.jl
  test/test_abstract_material.jl
  test/test_chaboche.jl
  test/test_chaboche_shear.jl
  test/test_idealplastic.jl
  test/test_idealplastic_shear.jl
  test/test_mecamatso.jl
  test/test_simulator.jl
  test/test_uniaxial_increment.jl
  test/test_viscoplastic.jl
Labels: enhancement
